version: '3.7'
services:
  mysql:
   container_name: app-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: products 
    MYSQL_ROOT_PASSWORD: password
    MYSQL_ROOT_HOST: '%'
   ports:
     - "3306:3306"
   restart: always

  app:
    restart: always
    build:
      context: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - mysql
    links:
      - mysql

